### PR TITLE
Update cimgui + imgui v1.86

### PR DESCRIPTION
**Pull request by mattrbeck**
#### Changes
This is just a simple change updating ImGui and cimgui to v1.86. I've followed the existing commit naming scheme in the repo.

#### Callouts
- I checked out the cimgui commit by tag rather than commit id, so the ImGui links in `src/obj.cr` and `src/types.cr` reference the tag rather than the commit. I saw you've done that previously, so I figured it's fine here
- I tried using `generate_demo.cr`, and while it produces the file on stdout and emits no errors, the file seems like an odd mix of Crystal and C code. I'm not sure if I'm missing some library on my machine or if something else is wrong, but I haven't looked further. As a result, I haven't included a subsequent "Port demo code from ImGui 1.86" commit in this PR

#### P.S.
Do you mind tagging versions on the commits similar to how they're tagged in ImGui and cimgui? It would be nice if this repo followed the same tagging convention :)

### CODE REVIEW

**Comment by oprypin** [comment]
> - I checked out the cimgui commit by tag rather than commit id, so the ImGui links in `src/obj.cr` and `src/types.cr` reference the tag rather than the commit. I saw you've done that previously, so I figured it's fine here

Actually that makes no difference at all, it's just that *cimgui* checked out *imgui* at a slightly later commit the previous time.

> - I tried using `generate_demo.cr`, and while it produces the file on stdout and emits no errors, the file seems like an odd mix of Crystal and C code.

Heh, that is indeed what it does, the rest of the way is manual, and to not lose the existing work, you're supposed to run `tools/update.cr`.

> Do you mind tagging versions on the commits similar to how they're tagged in ImGui and cimgui? It would be nice if this repo followed the same tagging convention :)

OK then, I'll do that.

**Comment by oprypin** [comment]
Thanks for the contribution. But I already have this exact commit locally for a few days, just not pushing it until I also port the demo code...

**Comment by mattrbeck** [comment]
Ah good to know on all of the above. Thanks for the quick follow-up!

**Comment by oprypin** [comment]
All done now, I think!

**Pull request closed without merging**
